#   Script:     p2.py
#   Full:       Project Euler Problem 2 Solution
#   Author:     Lee Terrell
#   Website:    4n6Lee.com
#
#   Problem Description:
#       Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#       By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

from datetime import datetime
startTime = datetime.now()

ceiling = 4000000
fibonacci = [0]
term = 1
sum = 0

# Construct the Fibonacci sequence in a list.
while term < ceiling:
    fibonacci.append(term)
    term = fibonacci[len(fibonacci) - 1] + fibonacci[len(fibonacci) - 2]

# Add every 3rd term of the Fibonacci sequence starting at index 3, or element '2.'
for s in range(3, len(fibonacci), 3):
    sum+=fibonacci[s]

print(sum)                              # Output the sum
print(datetime.now() - startTime)       # Output the execution time