#   Script:     p2.py
#   Full:       Project Euler Problem 2 Solution
#   Author:     Lee Terrell
#   Website:    4n6Lee.com
#
#   Problem Description:
#       Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#       By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

from datetime import datetime
startTime = datetime.now()

ceiling = 4000000
fibonacci = [0, 1]
sum = 0

while fibonacci[len(fibonacci) - 1] < ceiling:
    fibonacci.append(fibonacci[len(fibonacci) - 1] + fibonacci[len(fibonacci) - 2])

fibonacci.remove(fibonacci[len(fibonacci) - 1])

for s in range(3, len(fibonacci), 3):
    sum+=fibonacci[s]

print(sum)
print(datetime.now() - startTime)       # Output the execution time